name: Clang Format

on:
  push:
    paths:
      - ".github/workflows/clang-format-lint.yml"
      - "boards/**/*.c"
      - "include/**/*.h"
      - "src/**"
      - "drivers/**/*.c"
      - "drivers/**/*.h"
  pull_request:
    paths:
      - ".github/workflows/clang-format-lint.yml"
      - "boards/**/*.c"
      - "include/**/*.h"
      - "src/**"
      - "drivers/**/*.c"
      - "drivers/**/*.h"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: "."
          extensions: "h,c"
